# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: xgboost
  image: image
  command: "python3 -u main.py --operator=xgboost --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  storage:
   attachExistingPVCs:
    - name: mchennoufi-p-f41bb5ca8c5d42f8-kyber-pvc-33a7e00a26e24330
      mountPoint: /mnt/mchennoufi-p-f41bb5ca8c5d42f8-kyber-pvc-33a7e00a26e24330

  types:
    worker:
      count: 2
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
