# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: jobset
  image: image
  command: "python3 -u main.py --operator=jobset --sleep=500 --tb-write=True"
  storage:
   attachExistingPVCs:
    - name: mchennoufi-d-577440228dc04b13-tensorboard-e353c89345ff4729
      mountPoint: /mnt/mchennoufi-d-577440228dc04b13-tensorboard-e353c89345ff4729

  tensorboard:
    enabled: true

  types:
    master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
