# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json

kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: jobset
  image: image
  command: "python3 -u main.py --operator=jobset --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  storage:
   attachExistingPVCs:
    - name: mchennoufi-d-392698ae86c44ed6-pvc-test-342a97e0345747fa
      mountPoint: /mnt/mchennoufi-d-392698ae86c44ed6-pvc-test-342a97e0345747fa

  types:
    master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
